Implement build in Dockerfile
GoogleCloudPlatform/compute-daisy pull request #8
Opened 2022-02-16 23:35 UTC by EricEdens

This implements a Dockerfile for building daisy directly in the `compute-daisy` repo. It includes [container structure tests](https://github.com/GoogleContainerTools/container-structure-test) that validate its contents; I used the existing `gcr.io/compute-image-tools/daisy` image to create the tests.

Notably, the Dockerfile has conditional logic to add the `/workflows` directory. In [guest-test-infra](https://github.com/GoogleCloudPlatform/guest-test-infra) I'm adding a concourse pipeline that includes a step to add the workflows.

2022-02-17 00:04 UTC, hopkiw requested changes

2022-02-17 00:04 UTC, hopkiw commented on Dockerfile
> +# that doesn't include the daisy workflows. In councourse, we manually include
```suggestion
# that doesn't include the daisy workflows. In concourse, we manually include
```

2022-02-17 00:04 UTC, hopkiw commented on Dockerfile
> +RUN go mod download && go mod verify
redundant verify

```suggestion
RUN go mod download
```

2022-02-17 00:04 UTC, hopkiw commented on daisy_integration_tests/container_structure/base.yaml
> +#  Copyright 2022 Google Inc. All Rights Reserved.
i don't want to maintain tests like this. this is a mock, strictly meaning it just reminds you to update this second file for a class of changes.

2022-02-17 00:04 UTC, hopkiw commented on Dockerfile
> +WORKDIR /go/src/daisy
will this be the workdir of the final image?

2022-02-17 01:22 UTC, EricEdens commented on Dockerfile
> +RUN go mod download && go mod verify
Updated. I got the convention from [1], but after reading the `man` pages on each command, I agree that `verify` in unnecessary. 

1. https://hub.docker.com/_/golang

2022-02-17 01:22 UTC, EricEdens commented on Dockerfile
> +# that doesn't include the daisy workflows. In councourse, we manually include
Done!

2022-02-17 01:23 UTC, EricEdens commented on Dockerfile
> +WORKDIR /go/src/daisy
Nope, just for the layer. A nice thing about the container structure tests is that they verify the workdir (it's workdir: "").

2022-02-17 01:26 UTC, EricEdens commented on daisy_integration_tests/container_structure/base.yaml
> +#  Copyright 2022 Google Inc. All Rights Reserved.
The intent is to codify the current image's behavior, and ensure that the new image that we're building follows the same behavior.

The reason it's important to keep the test is that users expect these values to never change: the entrypoint should always be the same, the daisy binary should be executable, the workflows directory should have a particular name. If there's a test failure, then it means someone changed the Docker image such that existing customers would be broken.

2022-02-18 23:18 UTC, hopkiw commented on Dockerfile
> +WORKDIR /go/src/daisy
sgtm (i also looked it up out of curiosity)
for some reason i don't have a resolve comment on this PR so just take this as my acceptance :)

2022-02-18 23:19 UTC, hopkiw approved these changes

2022-02-19 00:39 UTC, EricEdens commented on daisy_integration_tests/container_structure/base.yaml
> +#  Copyright 2022 Google Inc. All Rights Reserved.
Sure, I'll defer to you on this since you have a lot of experience building other containers.

2022-02-22 16:37 UTC, adjackura approved these changes

2022-02-22 16:38 UTC, merged